namespace ja2 {
  export const enum ScreenIds {
    EDIT_SCREEN, // 0
    SAVING_SCREEN,
    LOADING_SCREEN,
    ERROR_SCREEN,
    INIT_SCREEN, // 4
    GAME_SCREEN,
    ANIEDIT_SCREEN,
    PALEDIT_SCREEN,
    DEBUG_SCREEN,
    MAP_SCREEN,
    LAPTOP_SCREEN, // 10
    LOADSAVE_SCREEN,
    MAPUTILITY_SCREEN,
    FADE_SCREEN,
    MSG_BOX_SCREEN,
    MAINMENU_SCREEN, // 15
    AUTORESOLVE_SCREEN,
    SAVE_LOAD_SCREEN,
    OPTIONS_SCREEN,
    SHOPKEEPER_SCREEN,
    SEX_SCREEN,
    GAME_INIT_OPTIONS_SCREEN, // 21
    DEMO_EXIT_SCREEN,
    INTRO_SCREEN, // 23
    CREDIT_SCREEN,
    QUEST_DEBUG_SCREEN,
    MAX_SCREENS,
  }
}
